title: Javier Valladares
description: Ingeniero Civil Matemático recién titulado, con amplios conocimientos en análisis de datos y modelamiento matemático. Experimentado en el uso de herramientas como Excel y Python, también, cuento con conocimientos intermedios de SQL y Power BI para el procesamiento, análisis y visualización de datos. Poseo una gran capacidad analítica y resolutiva. Apasionado por el rubro del análisis de datos y, además, comprometido con la mejora continua y el desarrollo profesional.
show_downloads: false
theme: jekyll-theme-minimal
